--CREATE
--Филми (име, датаНаИзлизане, времетраене, рейтинг)
CREATE TABLE FILMS(
    NAME VARCHAR(50) NOT NULL CONSTRAINT PK_FILMS PRIMARY KEY,
    RATING DECIMAL(3,1),
    GOESOUTDATE DATE,
    LENGTH TIME,
    CONSTRAINT CK_RATING CHECK (RATING >= 0 AND RATING <= 10)
);

--Трейлъри (датаНаИзлизане, имеНаФилм, времетраене)
CREATE TABLE TRAILERS(
   GOESOUTDATE DATE NOT NULL CONSTRAINT PK_TRAILERS PRIMARY KEY,
   FILMNAME VARCHAR(50) NOT NULL CONSTRAINT FK_TRAILERS_FILMS REFERENCES FILMS(NAME),
   LENGTH TIME
);

--Актьори (игралноИме, реалноИме, бройФилми)
CREATE TABLE ACTORS(
    FILMNAME VARCHAR(50) NOT NULL CONSTRAINT PK_ACTORS PRIMARY KEY,
    REALNAME VARCHAR (50) NOT NULL,
    COUNTOFACTING SMALLINT,
    CONSTRAINT CK_COUNTOFACTING CHECK (COUNTOFACTING >= 0 AND COUNTOFACTING <= 8)
);

--Участва (имеНаФилм, игралноИмеНаАктьор)
CREATE TABLE STARSIN(
    FILMNAME VARCHAR(50) NOT NULL CONSTRAINT FK_STARS_IN_F REFERENCES FILMS(NAME),
    ACTORNAME VARCHAR(50) NOT NULL CONSTRAINT FK_STARS_IN_AC REFERENCES ACTORS(FILMNAME),
    CONSTRAINT PK_STARS_IN PRIMARY KEY (FILMNAME, ACTORNAME)
);

--Директори (код, име)
CREATE TABLE DIRECTORS(
    CODE CHAR(3) NOT NULL CONSTRAINT PK_DIRECTORS PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);

--Ръководи (кодНаДиректор, имеНаФилм)
CREATE TABLE DIRECTS(
    CODEDIRECTOR CHAR(3) NOT NULL CONSTRAINT FK_DIRECT_DIR REFERENCES DIRECTORS(CODE),
    FILMNAME VARCHAR(50) NOT NULL CONSTRAINT FK_DIRECT_F REFERENCES FILMS(NAME),
    CONSTRAINT PK_DIRECT PRIMARY KEY (CODEDIRECTOR, FILMNAME)
);

--Книги (код, заглавие, годинаНаИздаване, имеНаАвтор, имеНаФилм)
CREATE TABLE BOOKS(
    CODE CHAR(4) NOT NULL CONSTRAINT PK_BOOKS_CODE PRIMARY KEY,
    TITLE VARCHAR(50),
    YEAR INT,
    AUTHOR VARCHAR(50),
    FILMNAME VARCHAR(50) CONSTRAINT BOOKS_FILMS REFERENCES FILMS(NAME),
    CONSTRAINT CK_YEAR CHECK(YEAR > 0)
);