--VIEWS
--VIEW_1
CREATE VIEW ACTORS_IN_FILM(COUNT_ACTORS)
AS 
	SELECT COUNT(*)
	FROM STARSIN
	WHERE FILMNAME = 'Harry Potter and the Order of the Phoenix';

--CALL VIEW
SELECT * FROM ACTORS_IN_FILM;

--VIEW_2
CREATE VIEW ACTORS_DIRECTORS(FILMNAME, ACTORNAME, CODEDIRECTOR)
AS 
	SELECT S.FILMNAME, S.ACTORNAME, D.CODEDIRECTOR
	FROM STARSIN S, DIRECTS D
	WHERE S.FILMNAME = D.FILMNAME AND S.ACTORNAME <> 'Percy Weasley';

--CALL VIEW
SELECT * FROM ACTORS_DIRECTORS;