--TRIGGER
--TRIGGER_1
CREATE TRIGGER INSERT_RATING
    NO CASCADE BEFORE INSERT ON FILMS
    REFERENCING NEW AS N
    FOR EACH ROW
    WHEN ( N.RATING IS NULL)
        SET N.RATING = 10;

--TRIGGER_2
CREATE TRIGGER DEL_ACT_TR
    AFTER DELETE ON ACTORS
    REFERENCING OLD AS O
    FOR EACH ROW
    WHEN ( O.FILMNAME = 'Harry Potter' )
    	CALL FN71890.act_hp(O.FILMNAME);
    	
DELETE FROM ACTORS
WHERE FILMNAME = 'Harry Potter';
    
CREATE PROCEDURE FN71890.act_hp(IN film_actor_name VARCHAR(50))
RESULT SETS 1
LANGUAGE SQL
SPECIFIC act_hp
BEGIN
	DECLARE cursor1 CURSOR WITH RETURN FOR SELECT * FROM ACTORS WHERE FILMNAME <> film_actor_name;
	OPEN cursor1;

END@